#!/bin/bash

# make sure path to this project is set
if [ ! -n "$POLICY_DIFFUSION" ]; then
    echo "Error: \$POLICY_DIFFUSION environment variable is not set"
    return
fi

# add python code to path
export PYTHONPATH=${POLICY_DIFFUSION}/lid:${PYTHONPATH}
export PYTHONPATH=${POLICY_DIFFUSION}/lid/etl:${PYTHONPATH}
export PYTHONPATH=${POLICY_DIFFUSION}/lid/utils:${PYTHONPATH}
export PYTHONPATH=${POLICY_DIFFUSION}/lid/evaluation:${PYTHONPATH}
export PYTHONPATH=${POLICY_DIFFUSION}/scripts:${PYTHONPATH}
